service: transcribe-audio

custom:
  service: api
  stage: ${env:SLS_STAGE, opt:stage, self:provider.stage, 'dev'}

provider:
  name: aws
  profile: ${file(../../../config/config.${self:custom.stage}.yml):profile}

  versionFunctions: false
  region: us-east-1
  memorySize: 128
  timeout: 30
  environment: ${file(../../../config/config.${self:custom.stage}.yml):environment}
  runtime: go1.x

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  

package:
  individually: ${file(../../../config/config.${self:custom.stage}.yml):packageIndidually}
  exclude:
    - ../../../**
  include:
    - ../../../bin/**

functions:

  ping:
    handler: bin/${self:custom.service}/ping
    events:
      - http:
          path: ping
          method: get
          cors: true
  
  upload:
    handler: bin/${self:custom.service}/upload
    events:
      - http:
          path: upload
          method: post
          cors: true